### ISSUE TITLE
Tokenomics docs overhaul

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/HydraDX-docs#161]
**Docs currently:** https://github.com/galacticcouncil/HydraDX-docs/blob/main/docs/tokenomics.md

Tokenomics page needs an overhaul to include:

- text explanation of the distribution breakdown and schedule, max supply, etc
- utility of HDX token
- two-token model with LRNA & HDX
- links to any other explainers in docs i.e. protocol fee burning LRNA or sending LRNA to HDX subpool

Some useful resources that can feed the doc:

https://hydradx.substack.com/p/feeding-every-hydrahead
https://hydradx.substack.com/p/hydradx-omnipool-part-2
https://hydradx.substack.com/p/hydradx-omnipool-part-1

**Comment by sarthak1dev** [comment]
I am not very familiar with hydraDX, but I would like to take this up and make a pr in a couple of weeks!!

**Comment by lolmcshizz** [comment]
This has been resolved but issue wasn't closed - thanks for the interest though!
