### ISSUE TITLE
[start_nominating] typos and incorrect in content 

### ISSUE THREAD

**Issue by SimonKraus** [galacticcouncil/HydraDX-docs#24]
https://docs.hydradx.io/start_nominating/#02-nominate-a-validator

The following passage needs to be rephrased @vgantchev : 

After clicking on the Nominate button you should see a popup called nominate validators. Here you can select on or more validators to nominate from the list of available validators. If you select multiple validators, you can disperse your stake in different proportions to the validators of your choice.

**Comment by jak-pan** [comment]
https://github.com/galacticcouncil/HydraDX-docs/commit/716a886715980242258786f3d6e2399d85e2bf7d
