### ISSUE TITLE
[performance_benchmark] needs reworking

### ISSUE THREAD

**Issue by SimonKraus** [galacticcouncil/HydraDX-docs#29]
https://docs.hydradx.io/performance_benchmark

is out of date

**Comment by jak-pan** [comment]
Now even more so

**Comment by vgantchev** [comment]
hi guys, can you please indicate what changed?

**Comment by SimonKraus** [comment]
@vgantchev  the bench-wizard should be autoinstalled now, the output is different than what's displayed. 
So best would be to re-run the bench and replace everything
