### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by ElevateCV** [galacticcouncil/HydraDX-docs#66]
Hi Everyone, 

We are ready with Polish translation on local branch ElavateCV/i18n-pl squashed and rebased with current main, but we don't have permission. Can you provide us a short instruction how to make a pull request?

Best Regards,

**Comment by SimonKraus** [comment]
Hi! There is no fork by the name of ElavateCV. 
It is just possible to merge across forks.
You would first need to fork the project. 
For translation stuff it's best to fork my fork https://github.com/SimonKraus/HydraDX-docs as I am supervising and testing all i18n stuff.

**Comment by ElevateCV** [comment]
Done, the pull request is ready.
